=== msd1kpei/OR03-ARMSAccount/OR03-ARMSAccount/xsd/ARMSAccount-request.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xs:schema xmlns="http://www.kpei.co.id/schema/Account.001" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://www.kpei.co.id/DataFeedNettedTradeRequest" xmlns:ns2="http://www.kpei.co.id/ARMSOfflineCollateralRequest" xmlns:ns3="http://www.kpei.co.id/RMOLNetPositionRequest" targetNamespace="http://www.kpei.co.id/schema/Account.001" elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xml="http://www.w3.org/XML/1998/namespace">
   <xs:element name="AccountInsert">
      <xs:annotation>
         <xs:documentation>ARMS Member delete inbound</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element name="header" type="middlewareHeader"/>
            <xs:element name="body">
               <xs:complexType>
                  <xs:sequence>
                     <xs:element name="Account" maxOccurs="unbounded">
                        <xs:complexType>
                           <xs:sequence>
                              <xs:element name="AccountType" type="xs:string"/>
                              <xs:element name="Description" type="xs:string"/>
                              <xs:element name="MemberID" type="xs:string"/>
                           </xs:sequence>
                           <xs:attribute name="id" type="xs:string"/>
                        </xs:complexType>
                     </xs:element>
                  </xs:sequence>
               </xs:complexType>
            </xs:element>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="AccountToARMS">
      <xs:annotation>
         <xs:documentation>e-CLEARS member to ARMS</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element name="header" type="middlewareHeader"/>
            <xs:element name="body">
               <xs:complexType>
                  <xs:sequence>
                     <xs:element ref="e-CLEARSAccount" maxOccurs="unbounded"/>
                  </xs:sequence>
               </xs:complexType>
            </xs:element>
            <xs:element name="ext" type="expandableVariable"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:complexType name="expandableVariable">
      <xs:annotation>
         <xs:documentation>Array of variable for extending parameters</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="value" minOccurs="0" maxOccurs="unbounded">
            <xs:annotation>
               <xs:documentation>value of parameter</xs:documentation>
            </xs:annotation>
            <xs:complexType>
               <xs:simpleContent>
                  <xs:extension base="xs:string">
                     <xs:attribute name="id" type="xs:string">
                        <xs:annotation>
                           <xs:documentation>name of parameter</xs:documentation>
                        </xs:annotation>
                     </xs:attribute>
                  </xs:extension>
               </xs:simpleContent>
            </xs:complexType>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="middlewareHeader">
      <xs:annotation>
         <xs:documentation>Standard Middleware Header</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="asAt" type="xs:dateTime">
            <xs:annotation>
               <xs:documentation>timestamp; ex. 2010-01-01T01:01:01 </xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="source" type="xs:string">
            <xs:annotation>
               <xs:documentation>source system; ex. Datafeed</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
      <xs:attribute name="id" type="xs:string">
         <xs:annotation>
            <xs:documentation>id for distinguish between message; can be sequence or filename_yyyymmddh24miss</xs:documentation>
         </xs:annotation>
      </xs:attribute>
   </xs:complexType>
   <xs:element name="e-CLEARSAccount">
      <xs:complexType>
         <xs:sequence>
            <xs:element name="AccountID" type="xs:string"/>
            <xs:element name="AccountType" type="xs:string"/>
            <xs:element name="Description" xml:base="" type="xs:string"/>
            <xs:element name="MemberID" type="xs:string"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
</xs:schema>

=== msd1kpei/OR03-ARMSAccount/OR03-ARMSAccount/public_html/assignTo_msg_eCLEARSAccount2-Source.xml
<?xml version='1.0' encoding='UTF-8'?>
<AccountToARMS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.kpei.co.id/schema/Account.001 file:/D:/00.%20PROJECTS/MWI/OR03-ARMSAccount/xsd/ARMSAccount-request.xsd" xmlns="http://www.kpei.co.id/schema/Account.001">
   <header id="id1">
      <asAt>2011-07-27T11:14:10.076</asAt>
      <source>source2</source>
   </header>
   <body>
      <e-CLEARSAccount>
         <AccountID>AccountID3</AccountID>
         <AccountType>AccountType4</AccountType>
         <Description>Description5</Description>
         <MemberID>MemberID6</MemberID>
      </e-CLEARSAccount>
      <e-CLEARSAccount>
         <AccountID>AccountID7</AccountID>
         <AccountType>AccountType8</AccountType>
         <Description>Description9</Description>
         <MemberID>MemberID10</MemberID>
      </e-CLEARSAccount>
      <e-CLEARSAccount>
         <AccountID>AccountID11</AccountID>
         <AccountType>AccountType12</AccountType>
         <Description>Description13</Description>
         <MemberID>MemberID14</MemberID>
      </e-CLEARSAccount>
   </body>
   <ext>
      <value id="id15">string16</value>
      <value id="id17">string18</value>
      <value id="id19">string20</value>
   </ext>
</AccountToARMS>
